workflows:
  build-neyyarappflutter:
    name: Build NeyyarAppFlutter
    max_build_duration: 60
    environment:
      flutter: 3.22.0
      xcode: latest
      java: 17
      vars:
        BUILD_NAME: "3.3.0"
        BUILD_NUMBER: "132"

    cache:
      cache_paths:
        - "$FLUTTER_ROOT/.pub-cache"
        - ".dart_tool"
        - "build"
        - "**/node_modules"


    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "*"
          include: true

    scripts:
      - name: Set up environment
        script: |
          echo "Setting up Flutter environment..."
          flutter --version

      - name: Install dependencies
        script: flutter pub get

      - name: Analyze code
        script: flutter analyze

      - name: Run tests
        script: flutter test

      - name: Build Android APK
        script: |
          flutter build apk --release \
          --build-name=$BUILD_NAME \
          --build-number=$BUILD_NUMBER \
          --dart-define=flutterVersionCode=$BUILD_NUMBER \
          --dart-define=flutterVersionName=$BUILD_NAME

      - name: Build Android AppBundle
        script: |
          flutter build appbundle --release \
           --build-name=$BUILD_NAME \
           --build-number=$BUILD_NUMBER

      - name: Build iOS
        script: |
         flutter build ios --release --no-codesign \
          --build-name=$BUILD_NAME \
          --build-number=$BUILD_NUMBER

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/app/outputs/bundle/release/app-release.aab
      - build/ios/ipa

    publishing:
      email:
        recipients:
          - sujith.ks@wayvida.com
        notify:
          success: true
          failure: true
